version: '3.8'
services:
  pg:
    image: postgres:16.4
    environment:
      POSTGRES_DB: ${DB_USER}
      POSTGRES_USER: ${DB_PASS}
      POSTGRES_PASSWORD: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata: